# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

version = 1
SPDX-PackageName = "Kdenlive Test Suite"
SPDX-PackageSupplier = "kdenlive@kde.org"
SPDX-PackageDownloadLocation = "https://invent.kde.org/multimedia/kdenlive-test-suite"

[[annotations]]
path = ["projects/**", "reference/**", "projects/footage/smpte-colors.mlt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["pics/pnsr.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["fonts/freemono/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Authors of the GNU FreeFont project"
SPDX-License-Identifier = "GPL-3.0-or-later WITH Font-exception-2.0"

[[annotations]]
path = ["resources/emblem-error.svg", "resources/emblem-checked.svg"]
SPDX-FileCopyrightText = "2014 Uri Herrera <uri_herrera@nitrux.in> and others"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["projects/footage/sharon-pittaway-iMdsjoiftZo-unsplash.jpg"]
SPDX-FileCopyrightText = "2016 Sharon Pittaway"
SPDX-License-Identifier = "CC0-1.0"
